name: cil
channels:
  - pytorch
  - ai-staging
  - conda-forge
  - huggingface
dependencies:
  - python=3.10
  - pip=25.1
  # Exploratory Analysis
  - matplotlib=3.10.0
  - nltk=3.9.1
  - wordcloud=1.9.4
  # ML
  - pytorch=2.5.1
  - scikit-learn=1.6.1
  # Hugging Face
  - datasets=3.6.0
  - transformers=4.51.3
  - evaluate=0.4.3
  # Language Models
  - llama.cpp=0.0.4877
  # Non-Conda Packages
  - pip:
      - lmql==0.7.3
