name: cil
channels:
  - pytorch
  - conda-forge
  - huggingface
dependencies:
  - python=3.10
  # Exploratory Analysis
  - matplotlib=3.10.0
  - nltk=3.9.1
  - wordcloud=1.9.4
  # ML
  - pytorch=2.5.1
  - scikit-learn=1.6.1
  # Hugging Face
  - datasets=3.5.1
  - transformers=4.49.0
  - evaluate=0.4.1
