name: cil
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.12
  - pip=25.1
  # Exploratory Analysis
  - matplotlib=3.10.3
  - nltk=3.9.1
  - wordcloud=1.9.4
  # ML
  - pytorch=2.5.1
  - scikit-learn=1.6.1
  # Hugging Face
  - datasets=3.6.0
  - transformers=4.51.3
  - evaluate=0.4.3
  - tensorboard=2.19.0
  # Non-Conda Packages
  - pip:
      - llama-cpp-python==0.3.9
      - lightning==2.5.1
      - accelerate==1.6.0
